services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-iot-frio
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: postgres-iot-frio
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: UTC
    volumes:
      - postgres_iot_frio_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_iot_frio_data:
  mosquitto_data:
  mosquitto_log: